apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "secret-santa.fullname" . }}-manager-rolebinding
  labels:
    {{- include "secret-santa.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "secret-santa.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ template "secret-santa.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}