{{- if .Values.webhook.enabled }}
{{- $serviceName := printf "%s-webhook-service" (include "pvc-chonker.fullname" .) }}
{{- $ca := genCA "pvc-chonker-ca" 365 }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionWebhook
metadata:
  name: {{ include "pvc-chonker.fullname" . }}-mutating-webhook-configuration
  labels:
    {{- include "pvc-chonker.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "pvc-chonker.fullname" . }}-serving-cert
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if .Values.webhook.certManager }}
    # CA bundle will be injected by cert-manager
    {{- else if .Values.webhook.caBundle }}
    caBundle: {{ .Values.webhook.caBundle }}
    {{- else }}
    caBundle: {{ $ca.Cert | b64enc }}
    {{- end }}
    service:
      name: {{ include "pvc-chonker.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1-persistentvolumeclaim
  failurePolicy: Fail
  name: mpvc.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - persistentvolumeclaims
  sideEffects: None
{{- end }}