{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvc-chonker.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pvc-chonker.labels" . | nindent 4 }}
spec:
  ports:
  - name: webhook-server
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "pvc-chonker.selectorLabels" . | nindent 4 }}
{{- end }}