apiVersion: v2
name: pvc-chonker
description: A cloud-agnostic Kubernetes operator for automatic PVC expansion
home: https://logiciq.ca/pvc-chonker
sources:
  - https://github.com/logicIQ/pvc-chonker

type: application

version: 0.3.0
appVersion: "0.3.0"

annotations:
  artifacthub.io/images: |
    - name: pvc-chonker
      image: logiciq/pvc-chonker:0.3.0
  artifacthub.io/license: Apache-2.0