{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "pvc-chonker.fullname" . }}-controller
  {{- if .Values.podMonitor.namespace }}
  namespace: {{ .Values.podMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "pvc-chonker.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "pvc-chonker.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: metrics
    {{- with .Values.podMonitor.scheme }}
    scheme: {{ . }}
    {{- end }}
    {{- with .Values.podMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.podMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    path: /metrics
    {{- with .Values.podMonitor.relabelings }}
    relabelings:
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.podMonitor.metricRelabelings }}
    metricRelabelings:
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}