apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "konductor.fullname" . }}-manager-rolebinding
  labels:
    {{- include "konductor.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "konductor.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ template "konductor.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}