apiVersion: v1
kind: Service
metadata:
  name: {{ template "konductor.fullname" . }}-controller-manager-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konductor.labels" . | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "konductor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: manager